# Generated by Django 5.2.4 on 2025-07-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(max_length=255)),
                ('code_ice', models.CharField(db_index=True, max_length=50)),
                ('secteur', models.TextField()),
                ('forme_juridique', models.CharField(choices=[('SA', 'SA'), ('SARL', 'SARL'), ('SNC', 'SNC'), ('SCS', 'SCS'), ('autre', 'Autre')], max_length=10)),
                ('ville', models.CharField(max_length=255)),
                ('adresse', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('activite', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('PP', 'Personne Physique'), ('PM', 'Personne Morale')], max_length=2)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('fax', models.CharField(blank=True, max_length=50, null=True)),
                ('site_web', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
                ('tel', models.CharField(blank=True, max_length=20, null=True)),
                ('certifications', models.TextField(blank=True, null=True)),
                ('cnss', models.CharField(blank=True, max_length=50, null=True)),
                ('identifiant_fiscal', models.CharField(blank=True, db_column='if', max_length=50, null=True)),
                ('patente', models.CharField(blank=True, max_length=50, null=True)),
                ('rc', models.CharField(blank=True, max_length=50, null=True)),
                ('en_activite', models.CharField(choices=[('oui', 'Oui'), ('non', 'Non')], default='oui', max_length=3)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('taille_entreprise', models.CharField(choices=[('PME', 'Petite et Moyenne Entreprise'), ('GE', 'Grande Entreprise'), ('SU', 'Startup')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('numero_telephone', models.CharField(max_length=20, unique=True)),
                ('username', models.CharField(max_length=150)),
                ('numero_carte', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('responsable', 'Responsable')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
