# Generated by Django 5.2.4 on 2025-07-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entreprise", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="numero_telephone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
