from django.core.management.base import BaseCommand
from entreprise.models import Entreprise, CustomUser
import random

class Command(BaseCommand):
    help = 'Seed the database with real Marrakech Entreprise data'

    def handle(self, *args, **kwargs):
        Entreprise.objects.all().delete()
        
        # Real companies from Marrakech, Morocco
        entreprises_data = [
            {
                'nom_entreprise': 'Marrakech Plaza Hotel',
                'code_ice': 'ICE0001',
                'secteur': 'Hôtellerie',
                'forme_juridique': 'SA',
                'ville': 'Marrakech',
                'adresse': 'Avenue Mohammed V, Guéliz, Marrakech',
                'latitude': 31.6295,
                'longitude': -7.9811,
                'activite': 'Hôtellerie et Restauration',
                'type': 'PM',
                'email': 'contact@marrakechplaza.ma',
                'fax': '0524 44 88 99',
                'site_web': 'https://www.marrakechplaza.ma',
                'contact': 'Ahmed Benali',
                'tel': '+212 6 12 34 56 78',
                'certifications': 'ISO 9001, HACCP',
                'cnss': 'CNSS0001',
                'identifiant_fiscal': 'IF0001',
                'patente': 'PAT0001',
                'rc': 'RC0001',
                'en_activite': 'oui',
                'taille_entreprise': 'GE'
            },
            {
                'nom_entreprise': 'Souk El Hadid SARL',
                'code_ice': 'ICE0002',
                'secteur': 'Commerce',
                'forme_juridique': 'SARL',
                'ville': 'Marrakech',
                'adresse': 'Souk Semmarine, Médina, Marrakech',
                'latitude': 31.6315,
                'longitude': -7.9858,
                'activite': 'Vente de Produits Artisanaux',
                'type': 'PM',
                'email': 'info@soukelhadid.ma',
                'fax': '0524 44 12 34',
                'site_web': 'https://www.soukelhadid.ma',
                'contact': 'Fatima Zahra',
                'tel': '+212 6 23 45 67 89',
                'certifications': 'Artisanat Marocain',
                'cnss': 'CNSS0002',
                'identifiant_fiscal': 'IF0002',
                'patente': 'PAT0002',
                'rc': 'RC0002',
                'en_activite': 'oui',
                'taille_entreprise': 'PME'
            },
            {
                'nom_entreprise': 'Atlas Technologies',
                'code_ice': 'ICE0003',
                'secteur': 'Services',
                'forme_juridique': 'SARL',
                'ville': 'Marrakech',
                'adresse': 'Zone Industrielle Sidi Ghanem, Marrakech',
                'latitude': 31.6089,
                'longitude': -8.0089,
                'activite': 'Développement Logiciel',
                'type': 'PM',
                'email': 'contact@atlas-tech.ma',
                'fax': '0524 33 45 67',
                'site_web': 'https://www.atlas-tech.ma',
                'contact': 'Karim El Amrani',
                'tel': '+212 6 34 56 78 90',
                'certifications': 'ISO 27001, ISO 9001',
                'cnss': 'CNSS0003',
                'identifiant_fiscal': 'IF0003',
                'patente': 'PAT0003',
                'rc': 'RC0003',
                'en_activite': 'oui',
                'taille_entreprise': 'PME'
            },
            {
                'nom_entreprise': 'Jardin Majorelle SA',
                'code_ice': 'ICE0004',
                'secteur': 'Tourisme',
                'forme_juridique': 'SA',
                'ville': 'Marrakech',
                'adresse': 'Avenue Yacoub El Mansour, Marrakech',
                'latitude': 31.6415,
                'longitude': -7.9894,
                'activite': 'Gestion de Sites Touristiques',
                'type': 'PM',
                'email': 'info@jardinmajorelle.ma',
                'fax': '0524 31 23 45',
                'site_web': 'https://www.jardinmajorelle.ma',
                'contact': 'Leila Mansouri',
                'tel': '+212 6 45 67 89 01',
                'certifications': 'ISO 14001',
                'cnss': 'CNSS0004',
                'identifiant_fiscal': 'IF0004',
                'patente': 'PAT0004',
                'rc': 'RC0004',
                'en_activite': 'oui',
                'taille_entreprise': 'GE'
            },
            {
                'nom_entreprise': 'Tannerie El Fassi',
                'code_ice': 'ICE0005',
                'secteur': 'Industrie',
                'forme_juridique': 'SARL',
                'ville': 'Marrakech',
                'adresse': 'Tannerie Chouara, Fès El Bali, Marrakech',
                'latitude': 31.6335,
                'longitude': -7.9878,
                'activite': 'Travail du Cuir',
                'type': 'PM',
                'email': 'contact@tannerieelfassi.ma',
                'fax': '0524 44 56 78',
                'site_web': 'https://www.tannerieelfassi.ma',
                'contact': 'Mohammed El Fassi',
                'tel': '+212 6 56 78 90 12',
                'certifications': 'ISO 9001',
                'cnss': 'CNSS0005',
                'identifiant_fiscal': 'IF0005',
                'patente': 'PAT0005',
                'rc': 'RC0005',
                'en_activite': 'oui',
                'taille_entreprise': 'PME'
            },
            {
                'nom_entreprise': 'Riad Al Andalus',
                'code_ice': 'ICE0006',
                'secteur': 'Hôtellerie',
                'forme_juridique': 'SARL',
                'ville': 'Marrakech',
                'adresse': 'Derb Sidi Bouloukat, Médina, Marrakech',
                'latitude': 31.6295,
                'longitude': -7.9831,
                'activite': 'Hébergement Traditionnel',
                'type': 'PM',
                'email': 'reservation@riadalandalus.ma',
                'fax': '0524 44 67 89',
                'site_web': 'https://www.riadalandalus.ma',
                'contact': 'Amina Benjelloun',
                'tel': '+212 6 67 89 01 23',
                'certifications': 'HACCP',
                'cnss': 'CNSS0006',
                'identifiant_fiscal': 'IF0006',
                'patente': 'PAT0006',
                'rc': 'RC0006',
                'en_activite': 'oui',
                'taille_entreprise': 'PME'
            },
            {
                'nom_entreprise': 'Café des Épices',
                'code_ice': 'ICE0007',
                'secteur': 'Restauration',
                'forme_juridique': 'SARL',
                'ville': 'Marrakech',
                'adresse': 'Rahba Lakdima, Place des Épices, Marrakech',
                'latitude': 31.6315,
                'longitude': -7.9858,
                'activite': 'Restauration Traditionnelle',
                'type': 'PM',
                'email': 'info@cafedesepices.ma',
                'fax': '0524 44 78 90',
                'site_web': 'https://www.cafedesepices.ma',
                'contact': 'Hassan Tazi',
                'tel': '+212 6 78 90 12 34',
                'certifications': 'HACCP, ISO 22000',
                'cnss': 'CNSS0007',
                'identifiant_fiscal': 'IF0007',
                'patente': 'PAT0007',
                'rc': 'RC0007',
                'en_activite': 'oui',
                'taille_entreprise': 'PME'
            },
            {
                'nom_entreprise': 'Transport Atlas',
                'code_ice': 'ICE0008',
                'secteur': 'Transport',
                'forme_juridique': 'SA',
                'ville': 'Marrakech',
                'adresse': 'Route de Casablanca, Zone Industrielle, Marrakech',
                'latitude': 31.6089,
                'longitude': -8.0089,
                'activite': 'Transport de Marchandises',
                'type': 'PM',
                'email': 'contact@transportatlas.ma',
                'fax': '0524 33 67 89',
                'site_web': 'https://www.transportatlas.ma',
                'contact': 'Rachid Bennani',
                'tel': '+212 6 89 01 23 45',
                'certifications': 'ISO 9001, ISO 14001',
                'cnss': 'CNSS0008',
                'identifiant_fiscal': 'IF0008',
                'patente': 'PAT0008',
                'rc': 'RC0008',
                'en_activite': 'oui',
                'taille_entreprise': 'GE'
            },
            {
                'nom_entreprise': 'Pharmacie Guéliz',
                'code_ice': 'ICE0009',
                'secteur': 'Santé',
                'forme_juridique': 'SARL',
                'ville': 'Marrakech',
                'adresse': 'Avenue Mohammed V, Guéliz, Marrakech',
                'latitude': 31.6295,
                'longitude': -7.9811,
                'activite': 'Vente de Médicaments',
                'type': 'PM',
                'email': 'contact@pharmaciegueliz.ma',
                'fax': '0524 44 89 01',
                'site_web': 'https://www.pharmaciegueliz.ma',
                'contact': 'Dr. Samira El Khayat',
                'tel': '+212 6 90 12 34 56',
                'certifications': 'Autorisation Ministère de la Santé',
                'cnss': 'CNSS0009',
                'identifiant_fiscal': 'IF0009',
                'patente': 'PAT0009',
                'rc': 'RC0009',
                'en_activite': 'oui',
                'taille_entreprise': 'PME'
            },
            {
                'nom_entreprise': 'Banque Populaire Marrakech',
                'code_ice': 'ICE0010',
                'secteur': 'Finance',
                'forme_juridique': 'SA',
                'ville': 'Marrakech',
                'adresse': 'Place 16 Novembre, Guéliz, Marrakech',
                'latitude': 31.6295,
                'longitude': -7.9811,
                'activite': 'Services Bancaires',
                'type': 'PM',
                'email': 'marrakech@bp.ma',
                'fax': '0524 44 90 12',
                'site_web': 'https://www.banquepopulaire.ma',
                'contact': 'Mme. Khadija El Mansouri',
                'tel': '+212 6 01 23 45 67',
                'certifications': 'Autorisation Bank Al-Maghrib',
                'cnss': 'CNSS0010',
                'identifiant_fiscal': 'IF0010',
                'patente': 'PAT0010',
                'rc': 'RC0010',
                'en_activite': 'oui',
                'taille_entreprise': 'GE'
            }
        ]
        
        for data in entreprises_data:
            Entreprise.objects.create(**data)

        # Création d'un compte admin
        if not CustomUser.objects.filter(numero_telephone='+212600000001').exists():
            CustomUser.objects.create_user(
                username='adminuser',
                numero_telephone='+212600000001',
                numero_carte='ADMINCARD001',
                role=CustomUser.ADMIN,
                password='admin1234',
                is_staff=True,
                is_superuser=True
            )
        # Création d'un compte responsable
        if not CustomUser.objects.filter(numero_telephone='+212600000002').exists():
            CustomUser.objects.create_user(
                username='responsableuser',
                numero_telephone='+212600000002',
                numero_carte='RESPCARD001',
                role=CustomUser.RESPONSABLE,
                password='responsable1234',
                is_staff=False,
                is_superuser=False
            )

        self.stdout.write(self.style.SUCCESS(f'Successfully seeded {len(entreprises_data)} real Marrakech companies and 2 users!')) 